ci: workflows: update for Zephyr v4.2
Update workflows, primarily pinning actions dependencies, updating
docker images and using the new `requirements-actions.txt` file from
upstream.

Temporarily add the `push: feature/zephyr_v4.2` trigger so we can test
the updated workflows.

Signed-off-by: Jordan Yates <jordan@embeint.com>

diff --git a/.github/workflows/documentation.yml b/.github/workflows/documentation.yml
--- a/.github/workflows/documentation.yml
+++ b/.github/workflows/documentation.yml
@@ -31,7 +31,7 @@ jobs:
     name: "Documentation Build (HTML)"
     runs-on: self-hosted
     container:
-      image: ghcr.io/zephyrproject-rtos/ci-repo-cache:v0.27.4.20241026
+      image: ghcr.io/zephyrproject-rtos/ci-repo-cache:v0.28.4.20250818
       options: '--entrypoint /bin/bash'
       volumes:
       - /repo-cache/embeint:/github/cache/embeint
@@ -41,7 +41,8 @@ jobs:
         # The latest CMake available directly with apt is 3.18, but we need >=3.20
         # so we fetch that through pip.
         CMAKE_VERSION: 3.20.5
-        DOXYGEN_VERSION: 1.12.0
+        DOXYGEN_VERSION: 1.14.0
+        DOXYGEN_MD5SUM: e761a5097ae20ecccfd02041925f102a
         BASE_REF: ${{ github.base_ref }}
         ZEPHYR_TOOLCHAIN_VARIANT: zephyr
     timeout-minutes: 10
@@ -64,12 +65,23 @@ jobs:
         git remote set-url origin ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
 
     - name: Checkout
-      uses: actions/checkout@v4
+      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
       with:
         ref: ${{ github.event.pull_request.head.sha }}
         path: infuse-sdk
         fetch-depth: 0
-        persist-credentials: false
+
+    - name: Set up Python
+      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
+      with:
+        python-version: 3.12
+        cache: pip
+        cache-dependency-path: infuse-sdk/scripts/requirements-actions.txt
+
+    - name: Install Python packages
+      working-directory: infuse-sdk
+      run: |
+        pip install -r scripts/requirements-actions.txt --require-hashes
 
     - name: Environment Setup
       working-directory: infuse-sdk
@@ -96,23 +108,25 @@ jobs:
         sudo apt-get install -y ninja-build graphviz lcov mscgen
         rm -rf doxygen-*
         wget --no-verbose "https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz"
+        echo "${DOXYGEN_MD5SUM}  doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz" | md5sum -c
+        if [ $? -ne 0 ]; then
+          echo "Failed to verify doxygen tarball"
+          exit 1
+        fi
         tar xf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
         echo "${PWD}/doxygen-${DOXYGEN_VERSION}/bin" >> $GITHUB_PATH
 
-    - name: cache-pip
-      uses: actions/cache@v4
+    - name: Set up Python
+      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
       with:
-        path: ~/.cache/pip
-        key: pip-${{ hashFiles('infuse-sdk/doc/requirements.txt') }}
+        python-version: 3.12
+        cache: pip
+        cache-dependency-path: zephyr/doc/requirements.txt
 
     - name: install-pip
-      working-directory: infuse-sdk
       run: |
-        sudo pip install -U setuptools wheel pip
-        pip install -r doc/requirements.txt
-        pip install west==${WEST_VERSION}
-        pip install cmake==${CMAKE_VERSION}
-        pip install coverxygen
+        pip install -r zephyr/doc/requirements.txt --require-hashes
+        pip install -r infuse-sdk/doc/requirements.txt
 
     - name: build-docs
       working-directory: infuse-sdk
@@ -133,12 +147,12 @@ jobs:
         DOC_TAG=${DOC_TAG} SPHINXOPTS="-q -t publish" make -C doc ${DOC_TARGET}
 
     - name: compress-docs
-      if: ${{ github.event_name == 'push' }}
+      if: 0
       run: |
         tar cfJ html-output.tar.xz --directory=infuse-sdk/doc/_build html
 
     - name: upload-build
-      if: ${{ github.event_name == 'push' }}
+      if: 0
       uses: actions/upload-artifact@v4
       with:
         name: html-output
@@ -146,14 +160,13 @@ jobs:
 
   doc-publish:
     name: Publish Documentation
-    if: ${{ github.event_name == 'push' }}
+    if: 0
     runs-on: ubuntu-22.04
     needs: doc-build-html
 
     steps:
     - name: Download html artifacts
       uses: actions/download-artifact@v4
-
 
     - name: Uncompress docs
       run: |
